// Generated by CoffeeScript 1.6.3
(function() {
  var Model, Module, ServerService, _;

  Module = {};

  window.DebuggerEngine = Module;

  _ = window.Utils;

  Model = window.DebuggerModel;

  Module.ProgramViewer = function($scope) {
    return $scope.program = new Model.ProgramView(20);
  };

  Module.ProgramControl = function($scope, $server) {
    return $scope.getLines = function(linestart) {
      return $server.getProblemLines($scope.debuggerProblem);
    };
  };

  Module.Server = ServerService = (function() {
    function ServerService(http) {
      this.http = http;
    }

    ServerService.prototype.getProblemLines = function(problem, line) {
      return this.http.get({
        url: "/getsource",
        data: {
          problem: problem,
          line: line
        }
      });
    };

    return ServerService;

  })();

  Module.DebuggerProblem = {
    transduce: true,
    link: function(scope, element, attributes) {
      return scope.debuggerProblem = attributes["debuggerProblem"];
    }
  };

  Module.DebuggerEngine = angular.module('debugger', []).controller("ProgramViewer", Module.ProgramViewer).controller("ProgramControl", ["ServerService", Module.ProgramControl]).directive("debuggerProblem", function() {
    return Module.DebuggerProblem;
  }).service("ServerService", ["$http", ServerService]);

}).call(this);

/*
//@ sourceMappingURL=DebuggerEngine.map
*/
