// Generated by CoffeeScript 1.6.3
(function() {
  var EmptyLineBlock, LINE_NUM_WIDTH, Line, Module, ProgramModel, ProgramView, assert, copy, extend, newElement, pad,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Module = {};

  window.ProgramModel = Module;

  ProgramModel = window.ProgramModel;

  extend = function(obj, mixin) {
    var method, name;
    for (name in mixin) {
      method = mixin[name];
      obj[name] = method;
    }
    return obj;
  };

  copy = function(obj) {
    return extend({}, obj);
  };

  newElement = function(tag) {
    return $(document.createElement(tag));
  };

  assert = function(condition, message) {
    if (!condition) {
      throw new Error("ASSERT: " + message);
    }
  };

  pad = function(str, num, char) {
    if (!char) {
      char = " ";
    }
    return str + (char * (num - str.length(num < str.length ? void 0 : 0)));
  };

  LINE_NUM_WIDTH = 3;

  ProgramModel.Line = Line = (function() {
    function Line(line, num) {
      this.line = line;
      this.num = num;
    }

    Line.prototype.isNum = function(num) {
      return num === this.num;
    };

    Line.prototype.toString = function() {
      return pad(this.num, LINE_NUM_WIDTH) + ": " + this.line;
    };

    return Line;

  })();

  ProgramModel.EmptyLineBlock = EmptyLineBlock = (function(_super) {
    __extends(EmptyLineBlock, _super);

    function EmptyLineBlock(num, endnum) {
      this.num = num;
      this.endnum = endnum;
      assert(this.num >= this.endnum, "Empty Line invariant: " + this.num + "-" + this.endnum);
    }

    EmptyLineBlock.prototype.isNum = function(num) {
      return (this.num <= num && num < this.endnum);
    };

    EmptyLineBlock.prototype.splitAroundOn = function(line) {
      var num, ret;
      assert(isNum(line.num), "Split must get line between " + this.num + "-" + this.endnum);
      ret = [line];
      num = line.num;
      if (num + 1 < this.endnum) {
        ret.append(new EmptyLineBlock(this.num + 1, this.endnum));
      }
      if (this.num < num) {
        ret.append(new EmptyLineBlock(this.num, num));
      }
      return ret;
    };

    EmptyLineBlock.prototype.toString = function() {
      return "###: Lines " + this.num + " to " + (this.endnum - 1) + " not yet known.";
    };

    return EmptyLineBlock;

  })(Line);

  ProgramModel.ProgramView = ProgramView = (function() {
    function ProgramView(numLines, lines) {
      this.numLines = numLines;
      this.lines = lines;
      if (this.lines == null) {
        this.lines = [new EmptyLineBlock(0, this.numLines)];
      }
    }

    ProgramView.prototype.findLine = function(num) {
      var curLine, i, _i, _len, _ref;
      _ref = this.lines;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        curLine = _ref[i];
        if (curLine.isNum(num)) {
          return i;
        }
      }
      return -1;
    };

    ProgramView.prototype.getLine = function(num) {
      var index;
      index = findLine(num);
      if (index !== -1) {
        return this.lines[index];
      } else {
        return null;
      }
    };

    ProgramView.prototype.setLine = function(line) {
      var curLine, index, num, _ref;
      assert(line.num < this.numLines, "Line number specified is out of program bounds");
      num = line.num;
      index = this.getLine(num);
      if (index === -1) {
        this.lines.append(line);
      }
      curLine = this.lines[index];
      if (curLine instanceof EmptyLineBlock) {
        return ([].splice.apply(this.lines, [index, index - index + 1].concat(_ref = curLine.splitAround(line))), _ref);
      } else {
        return this.lines[index] = line;
      }
    };

    ProgramView.prototype.setLines = function(lines) {
      var line, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = lines.length; _i < _len; _i++) {
        line = lines[_i];
        _results.push(this.setline(line));
      }
      return _results;
    };

    return ProgramView;

  })();

}).call(this);

/*
//@ sourceMappingURL=DebuggerEngine.map
*/
