// Generated by CoffeeScript 1.6.3
(function() {
  var Model, Module, ServerService, _;

  Module = {};

  window.DebuggerEngine = Module;

  _ = window.Utils;

  Model = window.DebuggerModel;

  Module.ProgramViewer = function($scope) {};

  Module.ProgramControl = function($scope, server) {
    return $scope.getLines = function(lineStart) {
      return server.getProblemLines($scope.problemId, lineStart, $scope.program);
    };
  };

  Module.Server = ServerService = (function() {
    function ServerService(http, location) {
      this.http = http;
      this.location = location;
    }

    ServerService.prototype.getProblemId = function() {
      return this.location.absUrl().split("/").slice(-1)[0];
    };

    ServerService.prototype.getProblemLines = function(problem, line, view) {
      var query;
      query = this.http.get("/debugger/getsource", {
        params: {
          problemId: problem,
          line: line
        }
      });
      return query.success(function(data) {
        return view.setLines((function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            line = data[_i];
            _results.push(Model.Line.fromJson(line));
          }
          return _results;
        })());
      });
    };

    return ServerService;

  })();

  Module.DebuggerProblem = {
    transduce: true,
    link: function(scope, element, attributes) {
      return scope.debuggerProblem = attributes["debuggerProblem"];
    }
  };

  Module.DebuggerEngine = angular.module('debugger', []).controller("ProgramViewer", Module.ProgramViewer).controller("ProgramControl", ["$scope", "ServerService", Module.ProgramControl]).directive("debuggerProblem", function() {
    return Module.DebuggerProblem;
  }).service("ServerService", ["$http", "$location", ServerService]).run([
    "$rootScope", "ServerService", function(scope, server) {
      scope.problemId = server.getProblemId();
      return scope.program = new Model.ProgramView(20);
    }
  ]);

}).call(this);

/*
//@ sourceMappingURL=DebuggerEngine.map
*/
