// Generated by CoffeeScript 1.6.3
(function() {
  var ClassView;

  ClassView = window.ClassView;

  $(function() {
    return $("[data-role='classmodel']").each(function() {
      return ClassView.initView($(this));
    });
  });

}).call(this);

/*
//@ sourceMappingURL=init.map
*/
