// Generated by CoffeeScript 1.6.3
(function() {
  var Model, Module, PROBLEM_TIMEOUT, ProblemInstance, ProblemTemplate, ProblemsManager, express, fs, getJsonFromFile, getProgramLinesFromFile, http, idCounter, problemNames, problemsManager;

  Module = {};

  module.exports = Module;

  express = require("express");

  http = require("http");

  fs = require("fs");

  Model = require("./DebuggerModel.coffee");

  PROBLEM_TIMEOUT = 2 * 60 * 1000;

  idCounter = 0;

  problemNames = ["problem"];

  getProgramLinesFromFile = function(fileName) {
    var i, line, _i, _len, _ref, _results;
    _ref = fs.readFileSync(__dirname + "/" + fileName, {
      encoding: "utf8"
    }).split("\n");
    _results = [];
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      line = _ref[i];
      _results.push(new Model.Line(line, i));
    }
    return _results;
  };

  getJsonFromFile = function(fileName) {
    return JSON.parse(fs.readFileSync(__dirname + "/" + fileName, {
      encoding: "utf8"
    }));
  };

  ProblemTemplate = (function() {
    function ProblemTemplate(file) {
      var data;
      data = getJsonFromFile(file);
      this.program = getProgramLinesFromFile(data.programFile);
      this.description = data.description.join("\n");
      this.language = data.language;
      this.outline = data.outline;
      this.tests = data.tests;
    }

    return ProblemTemplate;

  })();

  ProblemInstance = (function() {
    function ProblemInstance(template) {
      this.template = template;
      this.name = this.template.name;
      this.id = this.name + "~" + idCounter;
      idCounter++;
      this.score = 0;
      this.program = this.template.program.slice();
    }

    return ProblemInstance;

  })();

  ProblemsManager = (function() {
    function ProblemsManager(problemNames) {
      var name, _i, _len, _ref;
      this.problemNames = problemNames;
      this.templates = {};
      _ref = this.problemNames;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        name = _ref[_i];
        this.templates[name] = new ProblemTemplate(name);
      }
      this.instances = {};
    }

    ProblemsManager.prototype.hasInstance = function(id) {
      if (this.instances[id] != null) {
        this.resetTimer(id);
        return true;
      } else {
        return false;
      }
    };

    ProblemsManager.prototype.newInstance = function(name) {
      var instance,
        _this = this;
      instance = new ProblemInstance(this.templates[name]);
      this.instances[instance.id] = {
        instance: instance,
        timeout: setTimeout((function() {
          return _this.removeInstance(instance.id);
        }), PROBLEM_TIMEOUT)
      };
      return instance;
    };

    ProblemsManager.prototype.getInstance = function(id) {
      if (this.instances[id] == null) {
        return null;
      }
      this.resetTimer(id);
      return this.instances[id].instance;
    };

    ProblemsManager.prototype.removeInstance = function(id) {
      clearTimeout(this.instances[id].timeout);
      return delete this.instances[id];
    };

    ProblemsManager.prototype.resetTimer = function(id) {
      var instance,
        _this = this;
      instance = this.instances[id];
      clearTimeout(instance.timeout);
      return instance.timeout = setTimeout((function() {
        return _this.removeInstance(id);
      }), PROBLEM_TIMEOUT);
    };

    return ProblemsManager;

  })();

  problemsManager = new ProblemsManager(problemNames);

  Module.useExpressServer = function(app) {
    app.use("/debugger/js", express["static"](__dirname + "/js"));
    app.use("/debugger/less", express["static"](__dirname + "/less"));
    app.use("/debugger/images", express["static"](__dirname + "/images"));
    app.use("/debugger/", express["static"](__dirname));
    app.get("/debugger/problem/:problem", function(req, res) {
      var instance, invalidId, name, problem, _ref;
      problem = req.params.problem;
      if (problemsManager.hasInstance(problem)) {
        return res.sendfile(__dirname + "/index.html");
      }
      _ref = problem.split("~"), name = _ref[0], invalidId = _ref[1];
      instance = problemsManager.newInstance(name);
      if (instance == null) {
        return res.send(400, "Problem not found");
      }
      return res.redirect("/debugger/problem/" + instance.id);
    });
    app.get("/debugger/getinfo", function(req, res) {
      var instance;
      instance = problemsManager.getInstance(req.query.problemId);
      if (instance == null) {
        return res.send(400, "Problem not found");
      }
      return res.json(200, {
        name: instance.template.name
      });
    });
    return app.get("/debugger/getsource", function(req, res) {
      var instance, line;
      instance = problemsManager.getInstance(req.query.problemId);
      if (instance == null) {
        return res.send(400, "Problem not found");
      }
      line = parseInt(req.query.line);
      if (line == null) {
        return res.send(400, "Line argument not found");
      }
      return res.send(200, (function() {
        var _i, _len, _ref, _results;
        _ref = instance.program.slice(line, line + 7);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          line = _ref[_i];
          _results.push(line.toJson());
        }
        return _results;
      })());
    });
  };

}).call(this);

/*
//@ sourceMappingURL=server.map
*/
