// Generated by CoffeeScript 1.6.3
(function() {
  var Module, RacerView;

  Module = {};

  window.RaceCode = Module;

  RacerView = window.RacerView;

  $(function() {
    return $("[data-role='racerpuzzle']").each(function() {
      return RacerView.initPuzzle($(this));
    });
  });

}).call(this);

/*
//@ sourceMappingURL=code.map
*/
