// Generated by CoffeeScript 1.7.1
(function() {
  var Model, PlayerAuth, ProblemServer;

  Model = window.TeamerModel;

  PlayerAuth = (function() {
    PlayerAuth.$inject = ['$http'];

    function PlayerAuth($http) {
      this.http = $http;
    }

    PlayerAuth.prototype.submitLogin = function(name, callback) {
      return this.http({
        method: 'GET',
        url: '/teamerapi/login',
        params: {
          name: name
        }
      }).success((function(_this) {
        return function(data, status) {
          _this._setPlayer(data, name);
          return callback(_this.player, null);
        };
      })(this)).error(function(data, status) {
        return callback(null, data);
      });
    };

    PlayerAuth.prototype._setPlayer = function(id, name) {
      return this.player = new Model.Player(id, name);
    };

    return PlayerAuth;

  })();

  ProblemServer = (function() {
    ProblemServer.$inject = ['$http', '$location', 'playerAuth'];

    function ProblemServer($http, $location, playerAuth) {
      this.http = $http;
      this.player = playerAuth.player;
      this.problem = $location.path().split("/")[2];
    }

    ProblemServer.prototype.getFunctions = function(callback) {
      return this.http({
        method: 'GET',
        url: '/teamerapi/problem/' + this.problem + '/getFunctions',
        params: {
          id: this.player.id
        }
      }).success((function(_this) {
        return function(data, status) {
          return callback(data, null);
        };
      })(this)).error(function(data, status) {
        return callback(null, data);
      });
    };

    return ProblemServer;

  })();

  angular.module('teamer', ['ngRoute']).config(function($routeProvider, $locationProvider) {
    return $routeProvider.when('/login', {
      templateUrl: 'teamer/views/login.html',
      controller: 'LoginController'
    }).when('/problem/:problem/:stage', {
      templateUrl: 'teamer/views/problem.html',
      controller: 'ProblemController'
    }).otherwise({
      templateUrl: 'teamer/views/null.html',
      controller: 'InitController'
    });
  }).controller('LoginController', [
    '$scope', '$location', 'playerAuth', function($scope, $location, playerAuth) {
      return $scope.submitName = function() {
        $scope.loginError = false;
        return $scope.id = playerAuth.submitLogin($scope.loginname, function(player, error) {
          if (player) {
            return $location.path("");
          } else {
            return $scope.loginError = error;
          }
        });
      };
    }
  ]).controller('InitController', [
    '$location', 'playerAuth', function($location, playerAuth) {
      if (playerAuth.player) {
        console.log("INIT: player detected, redirecting to problem");
        return $location.path("/problem/sql/phase1");
      } else {
        console.log("INIT: no player found, redirecting to login");
        return $location.path("/login");
      }
    }
  ]).controller('ProblemController', [
    '$scope', '$location', 'problemServer', function($scope, $location, server) {
      $scope.ProblemStage = "Stage 1";
      $scope.ProblemName = server.problem;
      return server.getFunctions(function(data, error) {
        return $scope.functions = data;
      });
    }
  ]).service('playerAuth', PlayerAuth).service('problemServer', ProblemServer);

}).call(this);

//# sourceMappingURL=app.map
