// Generated by CoffeeScript 1.6.3
(function() {
  var Module;

  Module = {};

  if ((typeof module !== "undefined" && module !== null) && (module.exports != null)) {
    module.exports = Module;
  } else {
    window.Utils = Module;
  }

  Module.extend = function(obj, mixin) {
    var method, name;
    for (name in mixin) {
      method = mixin[name];
      obj[name] = method;
    }
    return obj;
  };

  Module.copy = function(obj) {
    return extend({}, obj);
  };

  Module.newElement = function(tag) {
    return $(document.createElement(tag));
  };

  Module.assert = function(condition, message) {
    if (!condition) {
      throw new Error("ASSERT: " + message);
    }
  };

  Module.pad = function(str, num, char) {
    var len;
    if (char == null) {
      char = " ";
    }
    len = (str + "").length;
    return str + (num > len ? Module.repeatStr(char, num - len) : "");
  };

  Module.repeatStr = function(str, count) {
    var i;
    return ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= count ? _i < count : _i > count; i = 0 <= count ? ++_i : --_i) {
        _results.push(str);
      }
      return _results;
    })()).join("");
  };

}).call(this);

/*
//@ sourceMappingURL=utils.map
*/
