// Generated by CoffeeScript 1.6.3
(function() {
  var ClassModel, Module;

  Module = {};

  window.ModelData = Module;

  ClassModel = window.ClassModel;

  ModelData.simple = {
    types: [new ClassModel.Interface("Drinkable"), new ClassModel.Class("Coffee"), new ClassModel.Class("MochaLatte")]
  };

}).call(this);
